[[redirects]]
  from = "/api/*"
  to = "http://52.78.121.235:8080/:splat"
  status = 200
  force = true

  [[redirects]]
  from = "novel/api/*"
  to = "http://52.78.121.235:8080/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
	force = false
